# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a05dd878a10a03fa32cdc622d405090"
name = "Cookies App"
handle = "cookiesapp2"
application_url = "https://zone-wool-chronic-something.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_content, read_customers,read_orders"

[auth]
redirect_urls = ["https://zone-wool-chronic-something.trycloudflare.com/auth/callback", "https://zone-wool-chronic-something.trycloudflare.com/auth/shopify/callback", "https://zone-wool-chronic-something.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
